### ISSUE TITLE
It won't connect to broker

### ISSUE THREAD

**Issue by gamesmusic454** [edusperoni/nativescript-plugins#3]
Hi, I've tried the example provided in angular and translated it into svelte, but at the time of connecting I get this error independant of the port used(tried with 1883 and 8000) `connection error: { "errorCode": 7, "errorMessage": "AMQJS0007E Socket error:undefined." }` 
This are my connection params:
```js
    let mqtt_host = 'broker.mqttdashboard.com';
    let mqtt_port = 1883;
    let mqtt_useSSL = false;
    let mqtt_path = '/mqtt';
    let mqtt_username = '';
    let mqtt_password = '';
    let mqtt_topic = 'ninja-topic';
    let mqtt_cleanSession = true;
```

**Comment by agentep98** [comment]
Yes, it doesn't work, if you wanna use the MQTT protocol you have to use ngx mqtt library(if you use angular with nativescript)

**Comment by edusperoni** [comment]
It does work. The problem most likely is that you're trying to connect insecurely (without ssl), and to do that you need to enable insecure connections in your app. Just use the ssl enabled port and it'll work.

**Comment by agentep98** [comment]
But it only works on ports 80 and 443?

**Comment by edusperoni** [comment]
This library supports mqtt over websockets, so it supports HTTP(S) communication over any port. If you opt into using non-ssl (http) on port 8000 for example, you need to add the same security exceptions on your app as if you were to connedto to any http API on port 8000 (insecure http connection). If you want to connect with https on port 8001 with a valid SSL certificate, everything will work as it should. If you have a self signed certificate, you also need security exceptions in the app.

These are iOS/Android limitations, not a limitation on this library.

The only limitation on this library is the same as the web mqtt library limitation: we only support mqtt over websockets.

I guess the best example is, if you can connect using the mqtt web client (https://www.hivemq.com/demos/websocket-client/), you can connect using this library, as we're using the same underlying library (paho mqtt) over websockets.

**Comment by agentep98** [comment]
Thank you very much, I tried a little while ago and it works perfectly on websockets with both encrypted and unencrypted connections, a few months ago I had tried and I don’t know why I couldn’t get it to work. Then I opted to use another library called ngx-mqtt for angular but I also had to use the plugin "@valor/nativescript-websockets" because the ngx-mqtt library was born to work on angular projects, but this library also works only on websocket.


Eu vi que você é brasileiro, muito obrigado por responder e te desejo um bom fim de semana!
